// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDiAT6HuI9mDJN5Sv-VvIXBSje28NJSaM',
    appId: '1:973489395308:web:8f9fa41e9f618ce40bea49',
    messagingSenderId: '973489395308',
    projectId: 'connectfirebase-92b37',
    authDomain: 'connectfirebase-92b37.firebaseapp.com',
    storageBucket: 'connectfirebase-92b37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdxa6DFt2Cii_cc8d_a-wGH9DFEX53keQ',
    appId: '1:973489395308:android:dcfa0a2f34de0b960bea49',
    messagingSenderId: '973489395308',
    projectId: 'connectfirebase-92b37',
    storageBucket: 'connectfirebase-92b37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP9S2HJisK0TbqQVBkUeLqOxuLcFd4X-w',
    appId: '1:973489395308:ios:582ff1b124c6c4a90bea49',
    messagingSenderId: '973489395308',
    projectId: 'connectfirebase-92b37',
    storageBucket: 'connectfirebase-92b37.appspot.com',
    iosClientId: '973489395308-a9orcrde21i71un0953g8em29p3qvhu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.signyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP9S2HJisK0TbqQVBkUeLqOxuLcFd4X-w',
    appId: '1:973489395308:ios:582ff1b124c6c4a90bea49',
    messagingSenderId: '973489395308',
    projectId: 'connectfirebase-92b37',
    storageBucket: 'connectfirebase-92b37.appspot.com',
    iosClientId: '973489395308-a9orcrde21i71un0953g8em29p3qvhu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.signyApp',
  );
}
